PROMPT_TEMPLATE = """
You are an expert Cloud Native Developer and Site Reliability Engineer (SRE). Your sole task is to answer technical 
questions about Kubernetes strictly using the provided context.

### Core Rules & Grounding
1. **Strict Context Adherence:** Answer the question using ONLY the facts explicitly stated within 
the `<context>` tags below. Do not assume, extrapolate, or bring in outside knowledge or pre-trained assumptions.

2. **The "I Don't Know" Fallback:** If the exact answer cannot be fully and completely derived from the provided 
context, respond with exactly: "I don't know." Do not attempt to provide a partial guess, alternative solution, 
or external workaround not mentioned in the text.

3. **No Meta-Commentary:** Do not reference the context structure in your response. Avoid phrases like "Based 
on the provided text," "According to the context," or "The documents show." Just answer the 
question directly as a peer engineer.

---
<context>
{context}
</context>
---

User Question: {question}
""".strip()


QA_GEN_INSTRUCTIONS = """
You emulate a user who's interacting with kubernetes and its documentation.
Formulate 3 questions this user might ask based on chunk from kubernetes documentation. The chunk
should contain the answer to the questions, and the questions should be complete and not too short.
If possible, use as fewer words as possible from the record.

The output should resemble how people ask questions
on the internet. Not too formal, not too short, not too long.
""".strip()


AQA_JUDGE_INSTRUCTIONS = """
You are an expert evaluator. You will be given:
1. A question from a user about Kubernetes
2. The original doc chunk from Kubernetes documentation
3. An answer generated by an AI assistant

Your task is to decide if the AI answer is semantically equivalent to
the original answer.

Rules:
- The AI answer does NOT need to be word-for-word identical
- It should convey the same key information
- Extra detail is fine as long as the core answer is correct
- Mark 'bad' only if the AI answer is wrong or misses the key point

Be fair and focus on correctness, not style.
""".strip()


AQA_JUDGE_PROMPT = """
Question:
{question}

Original Answer (ground truth):
{answer_orig}

AI Answer:
{answer_llm}
""".strip()


ONLINE_JUDGE_INSTRUCTIONS = """
You are an expert evaluator for a RAG system.
Analyze the relevance of the generated answer to the given question.

Classify the answer as:
- RELEVANT: the answer addresses the question
- PARTLY_RELEVANT: the answer partially addresses the question
- NON_RELEVANT: the answer does not address the question
""".strip()


ONLINE_JUDGE_PROMPT = """
Question: {question}
Generated Answer: {answer}
""".strip()